Adjust the styling and linked the username and profilepics
Afrilearn/New-White-Version pull request #189
Opened 2022-10-27 12:29 UTC by Kiyoonewton

Adjust the socialfeed styling link profile pic and username

2022-11-14 19:03 UTC, micheaol requested changes
Hi @Kiyoonewton , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! Please resolve the conflicts on the PR before requesting for review.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-11-14 20:10 UTC, micheaol requested changes
Hi @Kiyoonewton , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-11-14 20:10 UTC, micheaol commented on pages/dashboard/socialfeeds/common/centerFeed.jsx
>  const CenterFeed = () => {
@Kiyoonewton ,

Please find the error received below:

![image](https://user-images.githubusercontent.com/10332499/201755712-1a017863-6e5e-4698-9d1f-a141feedccc4.png)

2022-11-16 06:54 UTC, micheaol requested changes
Hi @Kiyoonewton , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-11-16 06:54 UTC, micheaol commented on components/features/dashboard/student/studentProfile/index.jsx
>                style={{
While you were resolving the conflicts, the hero page image has been tampered with. Kindly fix that ASAP.

## Your design:
![image](https://user-images.githubusercontent.com/10332499/202106216-61a0451a-7d8c-4386-a49f-f2943b24db6f.png)


## Current site:
![image](https://user-images.githubusercontent.com/10332499/202106353-ddb089c3-2672-4a54-8456-200f9be956ee.png)


Please make that adjustment and revert ASAP.

2022-11-16 10:25 UTC, Kiyoonewton commented
Add the adjustment already

2022-11-16 10:30 UTC, merged